!!python/object/apply:collections.defaultdict
dictitems:
  e_protein:
    data_dir: data/P0DTC4
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  m_protein:
    data_dir: data/P0DTC5
    whole:
      end: 222
      region_consurf_average: 5.036036036036036
      start: 1
  n_protein:
    CTD:
      end: 364
      region_consurf_average: 5.915492957746479
      start: 294
    NTD:
      end: 180
      region_consurf_average: 5.518248175182482
      start: 44
    data_dir: data/P0DTC9
    whole:
      end: 419
      region_consurf_average: 4.995226730310263
      start: 1
  nsp1:
    2gdt:
      end: 126
      region_consurf_average: 6.417391304347826
      start: 12
    3ld1:
      end: 562
      region_consurf_average: 4.79520697167756
      start: 104
    data_dir: data/P0DTC1
  nsp2:
    3ld1:
      end: 562
      region_consurf_average: 4.79520697167756
      start: 104
    dark_region:
      end: 818
      region_consurf_average: 4.37109375
      start: 563
    data_dir: data/P0DTC1
  nsp3:
    NAB:
      end: 2020
      region_consurf_average: 4.323943661971831
      start: 1879
    PL-Pro:
      end: 1878
      region_consurf_average: 4.629746835443038
      start: 1563
    SUD-C:
      end: 1562
      region_consurf_average: 4.739130434782608
      start: 1494
    SUD-M:
      end: 1493
      region_consurf_average: 4.695238095238095
      start: 1389
    Ubl1:
      end: 929
      region_consurf_average: 3.720720720720721
      start: 819
    dark_region_1027:
      end: 1368
      region_consurf_average: 4.277777777777778
      start: 1027
    data_dir: data/P0DTC1
    final_dark_region:
      end: 2763
      region_consurf_average: 4.920592193808883
      start: 2021
    macro_domain_region:
      end: 1193
      region_consurf_average: 3.8682634730538923
      start: 1027
    unnamed_dark_region:
      end: 1026
      region_consurf_average: 4.546391752577319
      start: 930
  nsp4:
    dark_region:
      end: 3172
      region_consurf_average: 4.750611246943765
      start: 2764
    data_dir: data/P0DTC1
    nsp4C:
      end: 3263
      region_consurf_average: 6.021978021978022
      start: 3173
  nsp8:
    data_dir: data/P0DTC1
    head_domain:
      end: 4140
      region_consurf_average: 5.6767676767676765
      start: 4042
    helical_segment:
      end: 4041
      region_consurf_average: 7.333333333333333
      start: 3943
  orf10:
    data_dir: data/A0A663DJA2
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  orf14:
    data_dir: data/P0DTD3
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  orf3a:
    data_dir: data/P0DTC3
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  orf6:
    data_dir: data/P0DTC6
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  orf7a:
    data_dir: data/P0DTC7
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  orf7b:
    data_dir: data/P0DTD8
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  orf9a:
    data_dir: data/P0DTD2
    whole:
      end: 99999999999
      region_consurf_average: null
      start: 1
  pp1a:
    dark_region_with_features:
      end: 11
      region_consurf_average: 6.636363636363637
      start: 1
    data_dir: data/P0DTC1
    nsp1:
      end: 180
      region_consurf_average: 6.072222222222222
      start: 1
    nsp10:
      end: 4392
      region_consurf_average: 6.690647482014389
      start: 4254
    nsp2:
      end: 818
      region_consurf_average: 4.564263322884012
      start: 181
    nsp2_dark_region_on_pp1a:
      end: 562
      region_consurf_average: 4.79520697167756
      start: 104
    nsp3:
      end: 2763
      region_consurf_average: 4.60668380462725
      start: 819
    nsp4:
      end: 3172
      region_consurf_average: 4.750611246943765
      start: 2764
    nsp5:
      end: 3569
      region_consurf_average: 6.071895424836601
      start: 3264
    nsp6:
      end: 3859
      region_consurf_average: 4.403448275862069
      start: 3570
    nsp7:
      end: 3942
      region_consurf_average: 6.759036144578313
      start: 3860
    nsp8:
      end: 4140
      region_consurf_average: 6.505050505050505
      start: 3943
    nsp9:
      end: 4253
      region_consurf_average: 6.150442477876106
      start: 4141
  pp1ab:
    dark_region_with_features:
      end: 11
      region_consurf_average: 5.181818181818182
      start: 1
    data_dir: data/P0DTD1
    nsp1:
      end: 180
      region_consurf_average: 5.633333333333334
      start: 1
    nsp10:
      end: 4392
      region_consurf_average: 5.489208633093525
      start: 4254
    nsp12:
      end: 5324
      region_consurf_average: 6.482832618025751
      start: 4393
    nsp13:
      end: 5925
      region_consurf_average: 6.088186356073211
      start: 5325
    nsp14:
      end: 6452
      region_consurf_average: 5.804554079696395
      start: 5926
    nsp15:
      end: 6798
      region_consurf_average: 5.265895953757226
      start: 6453
    nsp16:
      end: 7096
      region_consurf_average: 6.573825503355705
      start: 6799
    nsp2:
      end: 818
      region_consurf_average: 5.299373040752351
      start: 181
    nsp2_dark_region_on_pp1ab:
      end: 562
      region_consurf_average: 5.457516339869281
      start: 104
    nsp3:
      end: 2763
      region_consurf_average: 4.110539845758355
      start: 819
    nsp4:
      end: 3172
      region_consurf_average: 3.9388753056234718
      start: 2764
    nsp5:
      end: 3569
      region_consurf_average: 4.944444444444445
      start: 3264
    nsp6:
      end: 3859
      region_consurf_average: 2.8551724137931034
      start: 3570
    nsp7:
      end: 3942
      region_consurf_average: 4.481927710843373
      start: 3860
    nsp8:
      end: 4140
      region_consurf_average: 4.585858585858586
      start: 3943
    nsp9:
      end: 4253
      region_consurf_average: 5.212389380530974
      start: 4141
  spike_glycoprotein:
    data_dir: data/P0DTC2
    whole:
      end: 1273
      region_consurf_average: 5.132757266300079
      start: 1
